### ISSUE TITLE
testcase.mtx file missing

### ISSUE THREAD

**Issue by gopi-4** [divyanshu-talwar/Parallel-DFS#2]
please share the file.

**Comment by divyanshu-talwar** [comment]
The testcase.mtx file is a sample testcase and could be generated by the user. 

The input is expected to be in the matrix market (mm) file format which is best described [here](https://networkrepository.com/mtx-matrix-market-format.html).
For further clarity please find below the representation of the graph shown in Fig 1 on page 2 of [Report.pdf](https://github.com/divyanshu-talwar/Parallel-DFS/blob/master/Report.pdf) (assuming the mapping {a: 1, b: 2, c: 3, d: 4, e: 5, f: 6}).

```
%% MatrixMarket matrix coordinate pattern general
6 6 6
1 2
1 3
2 5
3 4
4 6
5 6
```
